In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
excel_data_filename = r'Basis State Industry List 071621.xlsx'
excel_industries_filename = r'Basis State Industries 210701.xlsx'
excel_industries_range = r'B6:B105'

In [3]:
training_df = pd.read_excel(os.path.join('data', excel_data_filename), 
                            sheet_name=r'Training List',
                            engine='openpyxl')
training_df

,Organization - ID,Organization - Name,Organization - Website,Organization - CB Description,Organization - Company Type,Organization - CB Industries,Organization - Employee Range,Organization - New Industry,Keyword,MetaKeyword,MetaDescription
0,440,Aston Martin Lagonda,https://www.astonmartin.comen-us/,Aston Martin Lagonda Global Holdings manufactu...,Acquirer,"Automotive, Leisure, Manufacturing, Product De...",1001-5000,Automotive - Car Manufacturing,NaN,NaN,NaN
1,898,Fiat Chrysler Auto,https://www.fcagroup.comen-US/Pages/home.aspx,"Fiat Chrysler Automobiles designs, engineers, ...",Acquirer,"Automotive, Industrial Manufacturing, Manufact...",10001+,Automotive - Car Manufacturing,NaN,NaN,NaN
2,930,Ford Motor Company,https://www.ford.com,"Ford Motor Company, an automotive company, dev...",Acquirer,"Apps, Automotive, Manufacturing, Transportation",10001+,Automotive - Car Manufacturing,access,NaN,NaN
3,965,General Motors Company,https://www.gm.com,General Motors is a Detroit-based mutinational...,Acquirer,"Automotive, Enterprise Software, Manufacturing...",10001+,Automotive - Car Manufacturing,access,NaN,NaN
4,296,AARP,http://www.aarp.org,NaN,Acquirer,NaN,NaN,"Civic, Non-Profit and Membership Groups","benefits, website, leaving, provider, cancel, ...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2164,48844,Healthtrust Workforce Solutions,https://healthtrustjobs.com/,NaN,Acquirer,NaN,NaN,NaN,NaN,NaN,NaN
2165,48845,Signature Consultants,https://www.sigconsult.com/,NaN,Acquirer,NaN,NaN,NaN,NaN,NaN,NaN
2166,48846,Acro Service Corporation,https://www.acrocorp.com/,NaN,Acquirer,NaN,NaN,NaN,NaN,NaN,NaN
2167,48847,DISYS,https://www.disys.com/,NaN,Acquirer,NaN,NaN,NaN,NaN,NaN,NaN
2168,48848,Supplemental Health Care,https://www.shccares.com/,NaN,Acquirer,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
all_data_df = pd.read_excel(os.path.join('data', excel_data_filename), 
                            sheet_name=r'All Acquirers',
                            engine='openpyxl')
all_data_df

,Organization - ID,Organization - Name,Organization - Website,Organization - CB Description,Organization - Company Type,Organization - CB Industries,Organization - Employee Range,Organization - New Industry,Keyword,MetaKeyword,MetaDescription
0,49945,TeleTech,https://www.ttecjobs.com/,NaN,Acquirer,NaN,10001+,Telecommunications,"customer, technology, talent, community, caree...",NaN,NaN
1,31314,OPSIFY,http://www.opsify.com,"On-demand, technology-enabled business service...",Acquirer,"Business Development, Business Intelligence, C...",501-1000,Corporate Services - Scaled Outbound Operations,"operations, opsify, company, business, process...",NaN,NaN
2,49952,Callbox,https://www.callbox.com/,NaN,Acquirer,NaN,NaN,Corporate Services - Scaled Outbound Operations,"phone, practices, dental, veterinary, automoti...",NaN,NaN
3,49970,Quantum Workplace,http://www.quantumworkplace.com,NaN,Acquirer,NaN,51-100,SAAS - Finance/HR - Human Resources,"engagement, employee, success, teams, performa...",NaN,NaN
4,44273,UJET,https://ujet.co/,UJETÃ¢â‚¬â„¢s cloud contact center solutions help o...,Acquirer,"Call Center, Communications Infrastructure, Cu...",101-250,SAAS - Contact Center Software,"contact, experience, smartphone, customer, clo...",NaN,UJET is the world's first and only cloud conta...
...,...,...,...,...,...,...,...,...,...,...,...
48757,50826,Seattle Bank,https://www.seattlebank.com/,NaN,Acquirer,NaN,NaN,Finance/Banking - Bank,0,NaN,NaN
48758,50828,Civis Bank,https://civisbank.com/,NaN,Acquirer,NaN,NaN,Finance/Banking - Bank,0,NaN,NaN
48759,50829,OV Loop,https://www.ovloop.com/,NaN,Acquirer,NaN,NaN,Computer Software - Finance/Banking - Digital ...,0,NaN,NaN
48760,50830,Silverbills,https://silverbills.com/,NaN,Acquirer,NaN,NaN,Computer Software - Finance/Banking - Digital ...,0,NaN,NaN
48761,50831,First Republic Bank,https://www.firstrepublic.com/,NaN,Acquirer,NaN,NaN,Finance/Banking - Bank,0,NaN,NaN

In [5]:
from openpyxl import load_workbook

industries = []
wb = load_workbook(os.path.join('data', excel_industries_filename))
ws = wb[r'Industries']
for row in ws[excel_industries_range]:
    for cell in row:
        industries.append(cell.value)
        
industries

['Automotive - Car Manufacturing',
 'Biotechnology',
 'Civic, Non-Profit and Membership Groups',
 'Computer Hardware',
 'Computer Software',
 'Computer Software - C2C Marketplace',
 'Computer Software - Finance/Banking - Digital Banking',
 'Computer Software - Gig Marketplace',
 'Computer Software - Leisure, Sports and Recreation',
 'Computer Software - Online Education',
 'Consumer Product Manufacturing',
 'Consumer Services - Automotive',
 'Consumer Services - Cleaning Services',
 'Consumer Services - Real Estate Brokers',
 'Corporate Services',
 'Corporate Services - Consulting',
 'Corporate Services - Market Research',
 'Corporate Services - Performance Marketing Agency',
 'Corporate Services - Recruiting Agency',
 'Corporate Services - Scaled Client Success Operations',
 'Corporate Services - Scaled Outbound Operations',
 'Corporate Services - Trade Show Organizers',
 'Educational Services',
 'Energy and Environmental - Carbon Measurement & Mgmt',
 'Energy and Environmental - Carbon Offset Supplier',
 'Energy and Environmental - Oil and Gas',
 'Energy and Environmental - Utilities',
 'Finance/Banking - Bank',
 'Finance/Banking - Credit Union',
 'Finance/Banking - CUSO',
 'Finance/Banking - Financial Services',
 'Finance/Banking - Financial Services - Credit Card Issuer',
 'Finance/Banking - Finanical Services - Monitoring',
 'Food and Beverage - Grocery',
 'Insurance',
 'Leisure, Sports and Recreation - Fitness Brands',
 'Leisure, Sports and Recreation - Fitness Chains',
 'Leisure, Sports and Recreation - Fitness Technology',
 'Leisure, Sports and Recreation - Hotels & Resorts',
 'Leisure, Sports and Recreation - Lifestyle Brands',
 'Leisure, Sports and Recreation - Restaurants, Bars and Eateries',
 'Media - Educational Publishing',
 'Media - Publication Tool',
 'Media - Publishing',
 'Media - Social Media',
 'Private Equity',
 'Retail - Fashion',
 'Retail - General Retailers',
 'Retail - Internet Retail',
 'SAAS - Advertising Tech',
 'SAAS - Agtech',
 'SAAS - AI',
 'SAAS - AI - Data/Analytics',
 'SAAS - AI - Machine Learning',
 'SAAS - Automotive',
 'SAAS - Banking Platform',
 'SAAS - Cannabis',
 'SAAS - Construction',
 'SAAS - Contact Center Software',
 'SAAS - Contractor Engagement',
 'SAAS - Customer Service',
 'SAAS - Document Management',
 'SAAS - eCommerce',
 'SAAS - EdTech',
 'SAAS - Email Marketing',
 'SAAS - Energy',
 'SAAS - Feedback',
 'SAAS - Finance/HR - Accounting',
 'SAAS - Finance/HR - ERP',
 'SAAS - Finance/HR - Expense Reporting',
 'SAAS - Finance/HR - Human Resources',
 'SAAS - Finance/HR - Payroll',
 'SAAS - Finance/HR - Recruiting',
 'SAAS - GovTech',
 'SAAS - Hospitals and Healthcare - Dental',
 'SAAS - Hospitals and Healthcare - Medical',
 'SAAS - Leisure, Sports and Recreation - Fitness',
 'SAAS - Leisure, Sports and Recreation - Hospitality',
 'SAAS - Leisure, Sports and Recreation - Sports Training',
 'SAAS - Leisure, Sports and Recreation - Travel Management',
 'SAAS - Manufacturing',
 'SAAS - Marketing Tech',
 'SAAS - Marketing Tech - Event Management',
 'SAAS - Marketing Tech - Marketing Automation',
 'SAAS - Marketing Tech - SEO',
 'SAAS - NGO',
 'SAAS - Point of Sale',
 'SAAS - Public Safety',
 'SAAS - Sales  - AI/Sales Intelligence',
 'SAAS - Sales  - Chat',
 'SAAS - Sales  - CRM',
 'SAAS - Sales  - eSignature',
 'SAAS - Services Management',
 'SAAS - Transportation',
 'SAAS - Transportation - Shipping',
 'Telecommunications',
 'Transportation',
 'Transportation - Airline',
 'Transportation - Shipping',
 'Venture Capital']